### ISSUE TITLE
CSS selector output twisted

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites-6#165]
i got the following output from the compiler

``` css
.column.large-centered, .large-centered.columns {
    float: none;
    margin-left: auto;
    margin-right: auto; }
```

shouldn't it

``` css
.column.large-centered,
    .columns.large-centered {
        float: none;
        margin-left: auto;
        margin-right: auto
    }
```

this is on several positions in the output is it a general problem or a problem with my compiler?

``` css
.column.end,
.end.columns {
    float: left
}
.column.row,
.row.columns {
    float: none
}
```

also several blocks gets wrapped in a @media screen

``` css
@media screen {
    .row.small-collapse > .column, .row.small-collapse > .columns {
      padding-left: 0;
      padding-right: 0; }
    .row.small-uncollapse > .column, .row.small-uncollapse > .columns {
      padding-left: 0.9375rem;
      padding-right: 0.9375rem; } }
```
