### ISSUE TITLE
scsss compilation error in show-for-only visibility classes

### ISSUE THREAD

**Issue by michael-wilson** [zurb/foundation-sites-6#239]
the show-for-only($size) mixin gives an error when provided it with 5 breakpoint size classes including xxlarge, but not if provided 4 or 3.

it fails as it passes a null to the -zf-bp-to-em mixin which then passes an unchecked null to the unit() function. It works with 3 or 4 entries as by default the map has 5 entries. when the list has 5 entries then the -zf-map-next mixin returns null and all hell breaks loose.

i got round it by changing the show-for-only mixin to this

```scss
@mixin show-for-only($size) {
  $lower-bound: -zf-bp-to-em(map-get($breakpoints, $size)) - (1/16);
  $upper-bound: -zf-map-next($breakpoints, $size);

  @if $upper-bound == null {
    @media screen and (max-width: $lower-bound) {
      display: none !important;
    }
  }
  @else {
    $upper-bound: -zf-bp-to-em(-zf-map-next($breakpoints, $size));
    @media screen and (max-width: $lower-bound), screen and (min-width: $upper-bound) {
      display: none !important;
    }
  }
}
```

its not pretty but it got me working again.
