### ISSUE TITLE
Off-Canvas Sass Compiling Issues

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites-6#288]
For some reason, when I compile the Sass files, the off-canvas is-open-left and is-open-right classes are being nested, which is causing the off-canvas menu to not open.

Here is the output I am getting:
````CSS
.off-canvas {
  position: absolute;
  background: #fefefe;
  z-index: -1; }
  [data-whatinput="mouse"] .off-canvas {
    outline: 0; }
  .off-canvas.position-left {
    left: -250px;
    top: 0;
    width: 250px; }
    .off-canvas.position-left .is-open-left {
      -webkit-transform: translateX(250px);
      transform: translateX(250px); }
  .off-canvas.position-right {
    right: -250px;
    top: 0;
    width: 250px; }
    .off-canvas.position-right .is-open-right {
      -webkit-transform: translateX(-250px);
      transform: translateX(-250px); }
````

I'm running Node v0.12.0 and Sass 3.4.14.

For reference, here is how the output should look:
````CSS
.off-canvas {
  position: absolute;
  background: #fefefe;
  z-index: -1; }
  [data-whatinput="mouse"] .off-canvas {
    outline: 0; }
  .off-canvas.position-left {
    left: -250px;
    top: 0;
    width: 250px; }
    .is-open-left {
      -webkit-transform: translateX(250px);
          -ms-transform: translateX(250px);
              transform: translateX(250px); }
  .off-canvas.position-right {
    right: -250px;
    top: 0;
    width: 250px; }
    .is-open-right {
      -webkit-transform: translateX(-250px);
          -ms-transform: translateX(-250px);
              transform: translateX(-250px); }
````
