### ISSUE TITLE
Breakpoint text alignment classes are not working in F6A1

### ISSUE THREAD

**Issue by matt3224** [zurb/foundation-sites-6#292]
breakpoint text alignment classes don't work, as in they don't output css.

**Comment by rafibomb** [comment]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr"><a href="https://twitter.com/LittleDotMatt">@littledotmatt</a> <a href="https://twitter.com/ZURBfoundation">@zurbfoundation</a> neither does .uncentered.</p>&mdash; Chris Myers (@LittleDotChris) <a href="https://twitter.com/LittleDotChris/status/665212206779342848">November 13, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by rafibomb** [comment]
Thanks - we'll take a look!

**Comment by gakimball** [comment]
I believe this has been fixed in the latest version of the code (alpha 1 was published about two weeks ago). Here's the output I pulled from the CSS:

```css
.text-left {
  text-align: left; }

@media screen and (min-width: 32em) {
  .medium-text-left {
    text-align: left; } }

@media screen and (min-width: 64em) {
  .large-text-left {
    text-align: left; } }

.text-right {
  text-align: right; }

@media screen and (min-width: 32em) {
  .medium-text-right {
    text-align: right; } }

@media screen and (min-width: 64em) {
  .large-text-right {
    text-align: right; } }
```
