### ISSUE TITLE
Feedback: CSS class customization

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#58]
For the grid classes only, we messed around with the idea of making the default CSS editable through the mixin parameters. Here's what the mixin definition looks like:

```scss
@mixin foundation-grid(
  $row: 'row',
  $column: 'column',
  $column-row: 'column-row',
  $push: 'push',
  $pull: 'pull',
  $center: 'centered',
  $uncenter: 'uncenter',
  $collapse: 'collapse',
  $uncollapse: 'uncollapse',
  $offset: 'offset',
  $end: 'end',
  $expanded: 'expanded',
  $breakpoints: $breakpoint-classes
) {
}
```

It's an interesting feature that could be applied to *every* component, but we have two hangups:

**It makes the codebase even more complicated.** The Sass is already fairly abstract because we use component mixins, and this makes the CSS a little more abstract as well. Here's what the grid output looks like:

```scss
.#{$row} {
    @include grid-row;

    &.#{$collapse} {
      > .#{$column} { @include grid-col-collapse; }
    }

    // ...
}
```

**It sort of does the same thing as the component mixins.** The point of the component mixins is that you can write your own class structure for our components, and change the naming, nesting, etc. This *kind of* does that in a way that's easier, but also less flexible, because you can't modify how the classes nest.

**Does this feature seem useful?** We'd like to hear your thoughts.
